# Generated by Django 3.2.9 on 2021-11-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='game',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='match',
            name='odds1',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='match',
            name='odds2',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
