# Generated by Django 3.2.9 on 2022-06-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_match_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='datetime',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
