# Generated by Django 3.2.9 on 2022-06-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0006_match_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='type',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
